name: Build Docker Image

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'OldReferenceCode/**'
      - 'XMPP-ejabberd/**'
      - 'OldReferenceCode/**'
      - 'Files/Engine.ini'
  push:
    paths-ignore:
      - '*.md'
      - 'OldReferenceCode/**'
      - 'XMPP-ejabberd/**'
      - 'OldReferenceCode/**'
      - 'Files/Engine.ini'

env:
  IMAGE_NAME: ut4masterserver

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build --pull -t ${{ env.IMAGE_NAME }} -f ./UT4MasterServer/.docker/Dockerfile ./UT4MasterServer
      - name: Clean Up
        run: docker image rm ${{ env.IMAGE_NAME }}
